original_file = open('PP2\\LABS\\LAB6\\p_tasks\\ex7\\original_file.txt', 'r')
file_contents = original_file.read()
new_file = open('PP2\\LABS\\LAB6\\p_tasks\\ex7\\new_file.txt', 'w')
new_file.write(file_contents)
print('File compied successfully!')
original_file.close()
new_file.close()
